---
title: "hw-01"
author: "Your Name (S2210699)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)

edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}
# 
missing_values <- colSums(is.na(edibnb))
print(names(missing_values[missing_values > 0]))

perfect_reviews <- edibnb[edibnb$review_scores_rating == 100, ]
listing_with_highest_perfect_reviews <- perfect_reviews$id[which.max(table(perfect_reviews$id))]
print(listing_with_highest_perfect_reviews)


```


[1] "price"               
[2] "neighbourhood"       
[3] "bathrooms"           
[4] "bedrooms"            
[5] "beds"                
[6] "review_scores_rating"

ID of the listing that has the highest number of reviews with a perfect review score of 100% is: 51505


------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}
# remove this comment and add the code for Exercise 2 here

```


_Remove this text, and add your answer for Exercise 2 here._


------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}
# remove this comment and add the code for Exercise 3 here

```


_Remove this text, and add your answer for Exercise 3 here._



------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}
# remove this comment and add the code for Exercise 4 here

```


_Remove this text, and add your answer for Exercise 4 here._


------------------------------------------------------------------------------
